services:
    queryside:
        build: ./queryside
        platform: linux/amd64
    commandside:
        build: ./commandside
        platform: linux/amd64
        ports:
            - 8080:10001
    eventstore:
        build: ./eventstore
        platform: linux/amd64
    test:
        build: ./test
        platform: linux/amd64
    main:
        build: ./main
        platform: linux/amd64
